name: Deploy GCP Folder Security Connector

on:
  workflow_dispatch:   # Manual trigger
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up PowerShell
        uses: actions/setup-powershell@v2

      - name: Install Az PowerShell module
        run: |
          pwsh -Command "Install-Module -Name Az -Force -Scope CurrentUser -AllowClobber"

      - name: Run GCP Folder Connector Script
        shell: pwsh
        run: |
          ./test-gcp-folder-connector.ps1 `
            -SubscriptionId "${{ secrets.AZURE_SUBSCRIPTION_ID }}" `
            -TenantId "${{ secrets.AZURE_TENANT_ID }}" `
            -ClientId "${{ secrets.AZURE_CLIENT_ID }}" `
            -ClientSecret "${{ secrets.AZURE_CLIENT_SECRET }}" `
            -ResourceGroup "${{ secrets.AZURE_RESOURCE_GROUP }}" `
            -GCPFolderId "${{ secrets.GCP_FOLDER_ID }}" `
            -ManagementProjectId "${{ secrets.GCP_MANAGEMENT_PROJECT_ID }}" `
            -ManagementProjectNumber "${{ secrets.GCP_MANAGEMENT_PROJECT_NUMBER }}"
