name: Deploy GCP Folder Security Connector

on:
  workflow_dispatch:
    inputs:
      GCPFolderId:
        description: 'GCP Folder ID'
        required: true
      ManagementProjectId:
        description: 'GCP Management Project ID'
        required: true
      ManagementProjectNumber:
        description: 'GCP Management Project Number'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up PowerShell
        uses: PowerShell/setup-pwsh@v2
        with:
          version: '7.3.10'

      - name: Install Az PowerShell module
        run: pwsh -Command "Install-Module -Name Az -Force -Scope CurrentUser -AllowClobber"


      - name: Run GCP Folder Connector Script
        shell: pwsh
        run: |
          ./connector.ps1 `
            -SubscriptionId "c5fddee6-8712-4dd8-b580-637b37dc5472" `
            -TenantId "831de134-d871-4cd7-823a-eacb69c699c8" `
            -ClientId "449d0493-4b3a-4a76-ae09-438169332c20" `
            -ClientSecret "lqa8Q~mI7GboAa.-jNped64HA8o2dp2FPambocQf" `
            -ResourceGroup "kpmg-testing" `
            -GCPFolderId "93604753456" `
            -ManagementProjectId "sbx-sentinel-mde-dev-920788" `
            -ManagementProjectNumber "1031194949050"
