name: Deploy GCP Security Connector with ARM Template

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Login to Azure
      run: |
        az login --service-principal \
          --username "d47fb118-5c46-4069-801d-a7c945665e0f" \
          --password "NkG8Q~.FzKAZCNttyqvHxAwaeero5ciRepXKDa6Z" \
          --tenant "1172494f-68e2-4743-8ebb-b6916a1c681e"

    - name: Set subscription
      run: |
        az account set --subscription "f2e26c0b-8b27-4edd-b6f4-73edc39a4186"

    - name: Create ARM template file
      run: |
        cat > arm-template.json << 'EOF'
        {
            "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
            "contentVersion": "1.0.0.0",
            "parameters": {},
            "variables": {},
            "resources": [
                {
                    "type": "Microsoft.Security/securityConnectors",
                    "apiVersion": "2023-10-01-preview",
                    "name": "gcp-poc-connector",
                    "location": "eastus",
                    "properties": {
                        "hierarchyIdentifier": "93604753456",
                        "environmentName": "GCP",
                        "environmentData": {
                            "organizationalData": {
                                "organizationMembershipType": "Organization",
                                "organizationId": "1044632980853",
                                "workloadIdentityPoolId": "1172494f68e247438ebbb6916a1c681e"
                            }
                        },
                        "offerings": [
                            {
                                "offeringType": "CspmMonitorGcp",
                                "nativeCloudConnection": {
                                    "workloadIdentityProviderId": "cspm",
                                    "serviceAccountEmailAddress": "microsoft-defender-cspm@gcp-containers-dso-prod-189401.iam.gserviceaccount.com"
                                }
                            }
                        ]
                    }
                }
            ]
        }
        EOF

    - name: Validate ARM template
      run: |
        az deployment group validate \
          --resource-group "kpmg-testing" \
          --template-file "arm-template.json" \
          --parameters @-

    - name: Deploy ARM template
      run: |
        az deployment group create \
          --resource-group "kpmg-testing" \
          --template-file "arm-template.json" \
          --name "gcp-connector-deployment" \
          --parameters @-

    - name: Check deployment status
      run: |
        az deployment group show \
          --resource-group "kpmg-testing" \
          --name "gcp-connector-deployment" \
          --query properties.provisioningState

    - name: Verify security connector
      run: |
        echo "Waiting for deployment to complete..."
        sleep 30
        az security security-connector show \
          --name "gcp-poc-connector" \
          --resource-group "kpmg-testing" \
          --output table
